# Generated by Django 5.0.2 on 2024-03-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='placa',
            field=models.CharField(default='abc-11', max_length=10),
            preserve_default=False,
        ),
    ]
